package vista;

import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import modelo.Archivos;

/**
 *
 * @author josea
 */
public class VentaVista extends javax.swing.JDialog {

    Archivos conexion;

    ArrayList<String> listaProductos;
    ArrayList<String> listaClientes;

    /**
     * Creates new form VentaVistas
     */
    public VentaVista(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public VentaVista(java.awt.Frame parent, boolean modal, Archivos conexion, ArrayList<String> productos, ArrayList<String> clientes) {
        super(parent, modal);
        //this.conexion = conexion;
        //this.listaProductos = productos;
        //this.listaClientes = clientes;
        initComponents();
        //actualizarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelVenta = new javax.swing.JLabel();
        boxClientes = new javax.swing.JComboBox<>();
        boxProductos = new javax.swing.JComboBox<>();
        fieldValorProducto = new javax.swing.JTextField();
        fieldTotalProduc = new javax.swing.JTextField();
        fieldCantProducto = new javax.swing.JTextField();
        btnVender = new javax.swing.JButton();
        labelCliente = new javax.swing.JLabel();
        labelProduc = new javax.swing.JLabel();
        labelValUni = new javax.swing.JLabel();
        labelCant = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelVenta.setFont(new java.awt.Font("Sitka Banner", 3, 36)); // NOI18N
        labelVenta.setText("Venta");

        boxClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxClientesActionPerformed(evt);
            }
        });

        boxProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxProductosActionPerformed(evt);
            }
        });

        fieldValorProducto.setEditable(false);
        fieldValorProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldValorProductoActionPerformed(evt);
            }
        });

        fieldTotalProduc.setEditable(false);
        fieldTotalProduc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldTotalProducActionPerformed(evt);
            }
        });

        fieldCantProducto.setText("1");
        fieldCantProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCantProductoActionPerformed(evt);
            }
        });

        btnVender.setText("Vender");
        btnVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderActionPerformed(evt);
            }
        });

        labelCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCliente.setText("Cliente");

        labelProduc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelProduc.setText("Producto");

        labelValUni.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelValUni.setText("Valor Unidad");

        labelCant.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCant.setText("Cantidad");

        labelTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelTotal.setText("Total");

        btnCancelar.setText("Atras");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(labelTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelValUni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelProduc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelCant, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(boxProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldValorProducto)
                            .addComponent(fieldCantProducto)
                            .addComponent(fieldTotalProduc, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .addComponent(labelVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVender, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(labelVenta)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCliente))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelProduc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(24, 24, 24))
                    .addComponent(boxProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldValorProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelValUni))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCant)
                    .addComponent(fieldCantProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldTotalProduc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTotal))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVender, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void boxClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxClientesActionPerformed

    private void boxProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxProductosActionPerformed
        // TODO add your handling code here:
        /*for (String pro : listaProductos) {
            String[] datos = pro.split(";");
            if (boxProductos.getSelectedItem().toString().equals(datos[0])) {
                fieldValorProducto.setText(datos[1]);
                int cant = Integer.parseInt(fieldCantProducto.getText());
                double val = Double.parseDouble(datos[1]);
                double total = val * cant;
                fieldTotalProduc.setText(String.valueOf(total));
            }
        }*/
    }//GEN-LAST:event_boxProductosActionPerformed

    private void fieldValorProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldValorProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldValorProductoActionPerformed

    private void fieldTotalProducActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldTotalProducActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldTotalProducActionPerformed

    private void fieldCantProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCantProductoActionPerformed
        // TODO add your handling code here:
        try {
            double total = Integer.parseInt(fieldCantProducto.getText()) * Integer.parseInt(fieldValorProducto.getText());
            fieldTotalProduc.setText(String.valueOf(total));
        } catch (Exception e) {
            System.out.println("EFE");
        }
    }//GEN-LAST:event_fieldCantProductoActionPerformed

    private void btnVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVenderActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void actualizarDatos() {

        /*for (String c : listaClientes) {
            boxClientes.addItem(c);
        }
        for (String p : listaProductos) {

            String[] datos = p.split(";");

            boxProductos.addItem(datos[0]);

        }*/
    }

    public JComboBox<String> getBoxClientes() {
        return boxClientes;
    }

    public JComboBox<String> getBoxProductos() {
        return boxProductos;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public JButton getBtnVender() {
        return btnVender;
    }

    public JTextField getFieldCantProducto() {
        return fieldCantProducto;
    }

    public JTextField getFieldTotalProduc() {
        return fieldTotalProduc;
    }

    public JTextField getFieldValorProducto() {
        return fieldValorProducto;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxClientes;
    private javax.swing.JComboBox<String> boxProductos;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnVender;
    private javax.swing.JTextField fieldCantProducto;
    private javax.swing.JTextField fieldTotalProduc;
    private javax.swing.JTextField fieldValorProducto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelCant;
    private javax.swing.JLabel labelCliente;
    private javax.swing.JLabel labelProduc;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JLabel labelValUni;
    private javax.swing.JLabel labelVenta;
    // End of variables declaration//GEN-END:variables
}
